// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities;

[Keyless]
public partial class Catgory
{
    public int Id { get; set; }

    [Column("Catgory_Name")]
    [StringLength(20)]
    public string CatgoryName { get; set; }
}