// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities;

public partial class Order
{
    [Key]
    [Column("ORDER_ID")]
    public int OrderId { get; set; }

    [Column("ORDER_DATE", TypeName = "date")]
    public DateTime? OrderDate { get; set; }

    [Column("ORDER_SUM")]
    public int OrderSum { get; set; }

    [Column("USER_ID")]
    public int UserId { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    [ForeignKey("UserId")]
    [InverseProperty("Orders")]
    public virtual User User { get; set; }
}