// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities;

[Keyless]
public partial class Product
{
    public int Id { get; set; }

    [Column("Category_ID")]
    public int? CategoryId { get; set; }

    [Column("Product_Name")]
    [StringLength(10)]
    public string ProductName { get; set; }

    [Column("Product_Description")]
    [StringLength(10)]
    public string ProductDescription { get; set; }

    public int? Price { get; set; }

    [Column("Image_Path")]
    [StringLength(10)]
    public string ImagePath { get; set; }
}